version: "3.4"
services:
  redis:
    image: "redis:alpine"
    volumes:
      - ./volumes/.redis:/data
    ports:
      - "6379:6379"
  api:
    ports:
      - "8000:3000"
    depends_on:
      - redis
      - db
    image: hc_conerts_api_image
    build:
      dockerfile: ../api/Dockerfile
    volumes:
      - ../api:/usr/src/api
      - ../api/config/database.docker.yml:/usr/src/api/config/database.yml
    environment:
      RAILS_ENV: development
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_DB: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
  user_interface:
    build:
      dockerfile: ../user_interface/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../user_interface:/usr/src/user_interface
    environment:
      VITE_API_URL: ${VITE_API_URL}
  db:
    image: postgres:14.0
    ports:
      - "5433:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./volumes/.dbdata:/var/lib/postgresql/data/pgdata
